// This class is automatically included in FastlaneRunner during build

// This autogenerated file will be overwritten or replaced during build time, or when you initialize `match`
//
//  ** NOTE **
//  This file is provided by fastlane and WILL be overwritten in future updates
//  If you want to add extra functionality to this project, create a new file in a
//  new group so that it won't be marked for upgrade
//

class Matchfile: MatchfileProtocol {
    // If you want to enable `match`, run `fastlane match init`
    // After, this file will be replaced with a custom implementation that contains values you supplied
    // during the `init` process, and you won't see this message
    
    var appIdentifier: [String]{
        return ["io.automaticpackage.AutomaticPackage"]
    }
    
    var profileName: String? {
        return "WildcardYin"
    }
    
    var type: String{
        return "development"
    }
    
    var username: String{
        return "yinwan_ios@126.com"
    }
    
    var force: Bool{
        return true
    }
    
    var gitUrl: String{
        return "https://github.com/abu0306/AutomaticPackage.git"
    }
    
    var gitUserEmail: String{
        return "2261983469@qq.com"
    }
    
    var gitFullName: String{
        return "abu0306"
    }
        
}

// Generated with fastlane 2.152.0
